In [3]:
import torch
%matplotlib inline

* 入门

In [5]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.shape

torch.Size([12])

In [7]:
x.numel()

12

In [10]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

其中的每个元素都从均值为0，标准差为1的标准高斯分布中随机采样

In [12]:
torch.randn(3, 4)

tensor([[-1.3046,  0.9796,  0.5680, -0.9042],
        [-1.3561,  0.9126,  1.8727, -0.9016],
        [-1.5364, -0.2644,  0.7128,  1.3694]])

* 运算

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x+y, x-y, x*y, x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [14]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [16]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X,Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [17]:
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [18]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [21]:
X.sum()

tensor(66.)

In [22]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(3).reshape((1, 3))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1, 2]]))

In [24]:
x = a+b
x

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])

In [25]:
x - b

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])

In [26]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [27]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [29]:
X[2, 3] = 14
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 14.]])

In [30]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 14.]])

### 节省内存

In [33]:
before = id(Y)
before

2735887393400

In [34]:
Y = X +Y
id(Y)

2735887521336

这可能是不可取的，原因有两个：首先，我们不想总是不必要地分配内存。在机器学习中，我们可能有数百兆的参数，并且在一秒内多次更新所有参数。通常情况下，我们希望原地执行这些更新。其次，我们可能通过多个变量指向相同参数。如果我们不原地更新，其他引用仍然会指向旧的内存位置，这样我们的某些代码可能会无意中引用旧的参数。

In [37]:
z = torch.zeros_like(Y)
id(z)

2735887492904

In [38]:
z[:] = X + Y
id(z)

2735887492904

幸运的是，执行原地操作非常简单。我们可以使用切片表示法将操作的结果分配给先前分配的数组，例如Y[:] = <expression>。

如果在后续计算中没有重复使用X，我们也可以使用X[:] = X + Y或X += Y来减少操作的内存开销

In [39]:
A = X.numpy()
type(A)

numpy.ndarray

In [40]:
B = torch.tensor(A)
type(B)

torch.Tensor

In [41]:
A

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 14.]], dtype=float32)

In [42]:
B

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 14.]])

In [43]:
a = torch.tensor([3.2])
a

tensor([3.2000])

In [44]:
int(a)

3

In [45]:
float(a)

3.200000047683716

In [46]:
a.item()

3.200000047683716