In [1]:
import torch

In [10]:
x = torch.arange(4, requires_grad=True, dtype=torch.float32)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [13]:
print(x.grad)

None


In [14]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [15]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [16]:
x.grad == 4 * x

tensor([True, True, True, True])

In [17]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [18]:
y = x.sum()
y

tensor(6., grad_fn=<SumBackward0>)

In [19]:
y.backward()

In [20]:
x.grad

tensor([1., 1., 1., 1.])

In [23]:
y.backward()
x.grad

tensor([4., 4., 4., 4.])

In [24]:
help(torch.ones)

Help on built-in function ones:

ones(...)
    ones(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a tensor filled with the scalar value `1`, with the shape defined
    by the variable argument :attr:`size`.
    
    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Default: ``torch.strided``.
        device (:class:`torch.device`, optional): the desired device of returned tensor.
            Default: if ``None``, uses the current device for the default ten